### PR TITLE
fix(bulma): Add textarea class to text field

### LINKED ISSUE #13: Text field should add class 'textarea'
Thanks for making this!

Given a view:

```
<%= simple_form_for company do |form| %>
  <%= form.input :terms_and_conditions %>
<% end %> 
```

It renders as:
```
<textarea class="input text optional" name="company[terms_and_conditions]" id="company_terms_and_conditions" spellcheck="false"></textarea>
```

Bulma has a `textarea` class for that field type though https://bulma.io/documentation/form/textarea/ instead of `text`.

### PR DESCRIPTION
**Pull request by JuanVqz**
BEGIN_COMMIT_OVERRIDE
fix(bulma): Add textarea class to text field
[textarea Documentation](https://bulma.io/documentation/form/textarea/)

Closes #13
END_COMMIT_OVERRIDE

### CODE REVIEW

File: lib/generators/simple_form/theme/bulma/templates/config/initializers/simple_form_bulma.rb [hunk 1]
```diff
@@ -108,6 +108,17 @@
     b.use :hint, wrap_with: { tag: 'small', class: 'help' }
   end
 
+  # bulma vertical textarea field
+  config.wrappers :vertical_text_form, tag: 'div', class: 'field' do |b|
+    b.use :html5
+    b.use :placeholder
+    b.optional :readonly
+    b.use :label, class: 'label'
+    b.use :input, class: 'textarea', wrap_with: { tag: 'div', class: 'control' }, error_class: 'is-danger', valid_class: 'is-success'
```
Comment (JuanVqz) [inline lib/generators/simple_form/theme/bulma/templates/config/initializers/simple_form_bulma.rb:117]: https://bulma.io/documentation/form/textarea/

**Comment by JuanVqz** [comment]
@nickhammond this should fix it
